// <auto-generated />
using System;
using Fixeon.Domain.Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fixeon.Domain.Infraestructure.Migrations
{
    [DbContext(typeof(DomainContext))]
    [Migration("20260730201017_tickettag")]
    partial class tickettag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid?>("InteractionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("Filename");

                    b.Property<Guid>("SenderId")
                        .HasMaxLength(36)
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InteractionId");

                    b.HasIndex("TicketId");

                    b.ToTable("attachments", t =>
                        {
                            t.HasCheckConstraint("CK_Attachment_Ticket_Or_Interaction", "(\"TicketId\" IS NOT NULL AND \"InteractionId\" IS NULL) OR (\"TicketId\" IS NULL AND \"InteractionId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Departament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("Name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("departaments");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("interactions");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.OrganizationsSLA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int>("SLAInMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SLAPriority")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("organizationsSLAs");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Departament")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("tickets");
                });

            modelBuilder.Entity("Fixeon.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.ToTable("companies");
                });

            modelBuilder.Entity("Fixeon.Domain.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("tickettags", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid")
                        .HasColumnName("TagId");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("TicketId");

                    b.HasKey("TagId", "TicketId");

                    b.HasIndex("TicketId");

                    b.ToTable("tickettags", (string)null);
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Attachment", b =>
                {
                    b.HasOne("Fixeon.Domain.Core.Entities.Interaction", "Interaction")
                        .WithMany("Attachments")
                        .HasForeignKey("InteractionId");

                    b.HasOne("Fixeon.Domain.Core.Entities.Ticket", "Ticket")
                        .WithMany("Attachments")
                        .HasForeignKey("TicketId");

                    b.Navigation("Interaction");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Category", b =>
                {
                    b.HasOne("Fixeon.Domain.Entities.Organization", "Organization")
                        .WithMany("Categories")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Category_Organization");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Departament", b =>
                {
                    b.HasOne("Fixeon.Domain.Entities.Organization", "Organization")
                        .WithMany("Departaments")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Departament_Organization");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Interaction", b =>
                {
                    b.HasOne("Fixeon.Domain.Core.Entities.Ticket", "Ticket")
                        .WithMany("Interactions")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Fixeon.Domain.Core.ValueObjects.InteractionUser", "CreatedBy", b1 =>
                        {
                            b1.Property<Guid>("InteractionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("UserEmail")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("userEmail");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("userId");

                            b1.HasKey("InteractionId");

                            b1.ToTable("interactions");

                            b1.WithOwner()
                                .HasForeignKey("InteractionId");
                        });

                    b.Navigation("CreatedBy")
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.OrganizationsSLA", b =>
                {
                    b.HasOne("Fixeon.Domain.Entities.Organization", "Organization")
                        .WithMany("SLAs")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Tag", b =>
                {
                    b.HasOne("Fixeon.Domain.Entities.Company", "Company")
                        .WithMany("Tags")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("CompanyTags");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Ticket", b =>
                {
                    b.OwnsOne("Fixeon.Domain.Core.ValueObjects.Analyst", "AssignedTo", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AnalystEmail")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("analystEmail");

                            b1.Property<string>("AnalystId")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("analystId");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsOne("Fixeon.Domain.Core.ValueObjects.Analyst", "ClosedBy", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AnalystEmail")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("closedByName");

                            b1.Property<string>("AnalystId")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("closedById");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.OwnsOne("Fixeon.Domain.Core.ValueObjects.SLAInfo", "SLAInfo", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");

                            b1.OwnsOne("Fixeon.Domain.Core.ValueObjects.SLA", "FirstInteraction", b2 =>
                                {
                                    b2.Property<Guid>("SLAInfoTicketId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime?>("Accomplished")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("FirstInteractionAccomplished");

                                    b2.Property<DateTime?>("Deadline")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("FirstInteractionDeadline");

                                    b2.HasKey("SLAInfoTicketId");

                                    b2.ToTable("tickets");

                                    b2.WithOwner()
                                        .HasForeignKey("SLAInfoTicketId");
                                });

                            b1.OwnsOne("Fixeon.Domain.Core.ValueObjects.SLA", "Resolution", b2 =>
                                {
                                    b2.Property<Guid>("SLAInfoTicketId")
                                        .HasColumnType("uuid");

                                    b2.Property<DateTime?>("Accomplished")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("ResolutionAccomplished");

                                    b2.Property<DateTime?>("Deadline")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("ResolutionDeadline");

                                    b2.HasKey("SLAInfoTicketId");

                                    b2.ToTable("tickets");

                                    b2.WithOwner()
                                        .HasForeignKey("SLAInfoTicketId");
                                });

                            b1.Navigation("FirstInteraction")
                                .IsRequired();

                            b1.Navigation("Resolution")
                                .IsRequired();
                        });

                    b.OwnsOne("Fixeon.Domain.Core.ValueObjects.User", "CreatedByUser", b1 =>
                        {
                            b1.Property<Guid>("TicketId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("OrganizationId")
                                .HasMaxLength(36)
                                .HasColumnType("uuid")
                                .HasColumnName("OrganizationId");

                            b1.Property<string>("OrganizationName")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("OrganizationName");

                            b1.Property<string>("UserEmail")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("userEmail");

                            b1.Property<string>("UserId")
                                .IsRequired()
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("userId");

                            b1.HasKey("TicketId");

                            b1.ToTable("tickets");

                            b1.WithOwner()
                                .HasForeignKey("TicketId");
                        });

                    b.Navigation("AssignedTo");

                    b.Navigation("ClosedBy");

                    b.Navigation("CreatedByUser")
                        .IsRequired();

                    b.Navigation("SLAInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Fixeon.Domain.Entities.Company", b =>
                {
                    b.OwnsOne("Fixeon.Domain.Core.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CompanyId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Country");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("Number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Street");

                            b1.HasKey("CompanyId");

                            b1.ToTable("companies");

                            b1.WithOwner()
                                .HasForeignKey("CompanyId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Fixeon.Domain.Entities.Organization", b =>
                {
                    b.HasOne("Fixeon.Domain.Entities.Company", "Company")
                        .WithMany("Organizations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Fixeon.Domain.Core.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("City");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("Country");

                            b1.Property<string>("Neighborhood")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Neighborhood");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(6)
                                .HasColumnType("character varying(6)")
                                .HasColumnName("Number");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("Street");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("tickettags", b =>
                {
                    b.HasOne("Fixeon.Domain.Core.Entities.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fixeon.Domain.Core.Entities.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Interaction", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Fixeon.Domain.Core.Entities.Ticket", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("Fixeon.Domain.Entities.Company", b =>
                {
                    b.Navigation("Organizations");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("Fixeon.Domain.Entities.Organization", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Departaments");

                    b.Navigation("SLAs");
                });
#pragma warning restore 612, 618
        }
    }
}
